config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/article', to: 'static_pages#article'
  get '/job', to: 'static_pages#job'

  get '/article/new', to: 'articles#new'
  post '/articles/new', to: 'articles#add'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @article = Article.new
  end

  def add
    puts '>>>', article_params
    @article = Article.new(article_params)
    @article.save
    redirect_to @article
  end

  def show
    @article = Article.find(params[:id])
  end


  private
    # 健壮参数, 避免批量赋值带来的安全隐患
    def article_params
      params.require(:article).permit(:content)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/new.html.erb
<% provide(:title, '增加文章') %>
<h1>增加文章</h1>

<div class="row">

  <div class="">
    <%= form_for(@article, url: new_article_path) do |f| %>
      <%= f.kindeditor :content%>
      <%= f.submit "添加文章", class: "btn btn-primary" %>
    <% end %>
  </div>

</div>

app/views/articles/show.html.erb
<div>
  <h1>文章预览</h1>
  <div id="id-editor-article-show">
    <%== @article.content %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <% if true %>
          <li><%= link_to "添加新闻", '/article' %></li>
          <li><%= link_to "添加职位", '/job' %></li>
        <% else %>
          <li><%= link_to "Log in", '#' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= 'Cryptape' %></title>
  <%=	render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div id="id-div-main" class="container">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/static_pages/article.html.erb
<div>
  <h1>新闻管理</h1>
  <lu>
    <li><%= link_to "新闻列表", '/news' %></li>
    <li><%= link_to "增加新闻", '/news' %></li>
  </lu>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>登录或选择页面</h1>
   <div>这里是登录框</div>

</div>

app/views/static_pages/job.html.erb
<div>
  <h1>新闻管理</h1>
  <lu>
    <li>新闻列表</li>
    <li>增加新闻</li>
  </lu>
</div>